### ISSUE TITLE
.articele missing

### ISSUE THREAD

**Issue by haemeulrich** [StudioMercury/digital-publishing-tools-for-wordpress#9] opened 2015-09-03 15:52 UTC
I'm able to upload an article to the cloud. But when I go to the DPS Portal I get a ".article missing".
Then I tried the "update article folio" from inside the WP Plugin, then I got the following error:

Headers
HTTP/1.1 100 Continue

 HTTP/1.1 400 Bad Request
 Access-Control-Allow-Origin: *
 Content-Type: application/json;charset=UTF-8
 Date: Thu, 03 Sep 2015 15:51:14 GMT
 Server: APIP
 Content-Length: 115
 Connection: keep-alive

Body
{"code":"InvalidIngestionRequest","message":"Invalid Request: required header x-dps-client-request-id is missing."}

URL
https://ings.publish.adobe.io/publication/cc9129fa-3d33-4cbe-ae1f-0b9f0106891b/article/haeme-ist-draussen;version=1441295246820/contents/folioHeaders
HTTP/1.1 100 Continue

 HTTP/1.1 400 Bad Request
 Access-Control-Allow-Origin: *
 Content-Type: application/json;charset=UTF-8
 Date: Thu, 03 Sep 2015 15:51:14 GMT
 Server: APIP
 Content-Length: 115
 Connection: keep-alive

Body
{"code":"InvalidIngestionRequest","message":"Invalid Request: required header x-dps-client-request-id is missing."}

URL
https://ings.publish.adobe.io/publication/cc9129fa-3d33-4cbe-ae1f-0b9f0106891b/article/haeme-ist-draussen;version=1441295246820/contents/folio

**Comment by haemeulrich** [comment] 2015-09-07 11:22
Do you have any ideas here?

**Comment by haemeulrich** [comment] 2015-09-14 07:55
We would like to use the plugin in a first project. Do you have a fix for this issue here?
Thank you!

**Comment by jeffreyflores** [comment] 2015-09-25 20:40
Also happening for me. Once the post is created in the cloud and sent to DPS Content Producer, the .article is listed as missing. 
![screen shot 2015-09-25 at 4 45 01 pm](https://cloud.githubusercontent.com/assets/1922564/10111749/10fcaf7c-63a4-11e5-9ec6-cfeada7a4a45.png)

**Comment by StudioMercury** [comment] 2015-09-26 01:42
Hi @jeffreyflores,
This is actually normal. We'll be updating our documentation to explain this more in depth. 

When you click "Create in the Cloud" the plugin creates an article in Adobe DPS. It only creates the article (the same way you'd create a new article in Adobe DPS). Metadata, images and the .article will be missing because they haven't been pushed yet. 

We realize this may not make sense to first create a "skeleton" reference article and then push content into it - so we're going to do some thinking around how we name this command - or - we may make it so that this command creates the reference and then pushes metadata, images and .article all at once. 

I'm closing this issue since it's not a bug.

**Closed as completed by StudioMercury** 2015-09-26 01:42 UTC
